name: "Make Release"

on:
  push:
    branches:
      - "main"
      - "beta"  # If we ever vere to have one

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Uses .releaserc.json
      - name: Make a semantic-release
        if: steps.semantic.outputs.new_release_published == 'true'
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          tag_format: ${version}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_RELEASE_PACKAGE: ${{ github.repository }}
