name: Deploy website to GitHub Pages

on:
  release:
    types: [created]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: samurai

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --prod --base-href=/${{ github.repository.name }}/ |
          mv -R dist/samurai/browser/* dist/samurai/ |
          rm -rf dist/samurai/browser |
          cp dist/samurai/index.html dist/samurai/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./samurai/dist/samurai/
          publish_branch: gh-pages
          commit_message: Deploy to GitHub Pages (${{ github.sha }})
